// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using website_CLB_HTSV.Data;

#nullable disable

namespace website_CLB_HTSV.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240314055730_ini4")]
    partial class ini4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("website_CLB_HTSV.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLop")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaSV")
                        .IsUnique()
                        .HasFilter("[MaSV] IS NOT NULL");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.DangKyHoatDong", b =>
                {
                    b.Property<string>("MaDangKy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaHoatDong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThaiDangKy")
                        .HasColumnType("bit");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHoatDong");

                    b.HasIndex("MaSV");

                    b.ToTable("DangKyHoatDong");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.HoatDong", b =>
                {
                    b.Property<string>("MaHoatDong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("DaDangKi")
                        .HasColumnType("bit");

                    b.Property<bool>("DaThamGia")
                        .HasColumnType("bit");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MinhChung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenHoatDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoatDong");

                    b.ToTable("HoatDong");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Khoahoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLop")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSV");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Quyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaSV");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.ThamGiaHoatDong", b =>
                {
                    b.Property<string>("MaThamGiaHoatDong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("DaThamGia")
                        .HasColumnType("bit");

                    b.Property<string>("MaDangKy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaThamGiaHoatDong");

                    b.HasIndex("MaDangKy");

                    b.ToTable("ThamGiaHoatDong");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.TinTuc", b =>
                {
                    b.Property<string>("MaTinTuc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SinhVienMaSV")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("SinhVienMaSV");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.ApplicationUser", b =>
                {
                    b.HasOne("website_CLB_HTSV.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaChucVu");

                    b.HasOne("website_CLB_HTSV.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop");

                    b.Navigation("ChucVu");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.DangKyHoatDong", b =>
                {
                    b.HasOne("website_CLB_HTSV.Models.HoatDong", "HoatDong")
                        .WithMany()
                        .HasForeignKey("MaHoatDong");

                    b.HasOne("website_CLB_HTSV.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSV");

                    b.Navigation("HoatDong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.LopHoc", b =>
                {
                    b.HasOne("website_CLB_HTSV.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.SinhVien", b =>
                {
                    b.HasOne("website_CLB_HTSV.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaChucVu");

                    b.HasOne("website_CLB_HTSV.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop");

                    b.Navigation("ChucVu");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.TaiKhoan", b =>
                {
                    b.HasOne("website_CLB_HTSV.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSV");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.ThamGiaHoatDong", b =>
                {
                    b.HasOne("website_CLB_HTSV.Models.DangKyHoatDong", "DangKyHoatDong")
                        .WithMany()
                        .HasForeignKey("MaDangKy");

                    b.Navigation("DangKyHoatDong");
                });

            modelBuilder.Entity("website_CLB_HTSV.Models.TinTuc", b =>
                {
                    b.HasOne("website_CLB_HTSV.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienMaSV");

                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
